### ISSUE TITLE
Apply for OpenSource account at Docker hub

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-docker#160]
See https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

**Comment by schmunk42** [comment]
Yeah, saw that and didn't find a time to create a ticket.

@yiisoft/reviewers Did someone understand what was the final decision? :grinning: 
https://github.com/docker/hub-feedback/issues/2314#issuecomment-1474706634
You can still pull but not push? 

Would be bad for how us, since we were making daily/weekly builds. 
Should we delete all images to avoid users from pulling outdated images?
Or at least add a notice/echo in the entrypoint command?

But I think we need to move to another location, ghcr.io would be my preffered choice. WDYT?

CC: @handcode

**Comment by samdark** [comment]
If we apply for OpenSource program, nothing will change for us.

**Comment by schmunk42** [comment]
We can give it a try: https://www.docker.com/community/open-source/application/

Should I fill out the form or will do you it as a project lead?

**Comment by samdark** [comment]
Feel free to do it.

**Comment by schmunk42** [comment]
They reversed course https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/
