### ISSUE TITLE
unable to load mcrypt in `5.6-apache`

### ISSUE THREAD

**Issue by albertborsos** [yiisoft/yii2-docker#22]
I get the following error on image `5.6-apache`
<img width="1359" alt="kepernyofoto 2017-12-01 - 19 14 01" src="https://user-images.githubusercontent.com/7307145/33497036-cd504cea-d6cc-11e7-81ae-9ca6a19e11c4.png">

I added this line to my Dockerfile which solves this issue:

```
RUN docker-php-ext-install mcrypt
```

But this is not the correct solution because i got the following message in the build process

```
warning: mcrypt (mcrypt.so) is already loaded!
```

**Comment by schmunk42** [comment]
Mcrypt is deprecated since 7.1

> Warning This feature was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0.

From http://php.net/manual/en/intro.mcrypt.php

We are currently installing `mcrypt` via `pecl` which does not work for PHP 5.6. 

AFAIK Yii2 does not depend on `mcrypt`, so the question is, if we remove it altogether and add the installation of `mcrypt` to the docs, since it differs on PHP 5.6, 7.0 & 7.1 and 7.2. @yiisoft/core-developers

**Comment by samdark** [comment]
Removing it is fine. It's not required at all.
