### ISSUE TITLE
Name for the "offical" docker image?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-docker#3]
Ideas

- `yiisoft/php`
- `yiisoft/php-yii2`
- `yiisoft/yii2-php`

*ordered by my personal preference* 👀 

Others?

**Comment by samdark** [comment]
If it's just PHP w/o anything which is suitable for Yii only, I'd name it `yiisoft/php`.

**Comment by mikehaertl** [comment]
I'd call it `yiisoft/yii2-php` as that's what it is: PHP for yii2. Alternatively `php-yii2`. I find `php` to short: `yiisoft/` is basically only a namespace so `php` would be missing the link to yii2. Also consider that there may be other PHP projects under `yiisoft/` some day - which require their own docker image.

**Comment by schmunk42** [comment]
> I find `php` to short

I'd never have expected to hear that from you 😆 

Technically speaking we would have to put that at the end:

- `yiisoft/php:7-yii2`
- `yiisoft/php:7.1.2-fpm-yii2`
- `yiisoft/php:5-alpine-yii2`

Since we're extending from this image.

**Comment by mikehaertl** [comment]
@schmunk42 But the `yii2` part is static because *all* our images are for yii2. You'd have to add it to *all* images. That's why it belongs to the name. And again this doesn't protect you from later naming conflicts: Later there could be a `yiisoft/wuu` framework (or another that we can't foresee which needs it's own docker image). The docker images for that should be kept in a separate repo and be called `yiisoft/php-wuu` or `yiisoft/wuu-php`.

**Comment by schmunk42** [comment]
That's true ;) 

So let's go with this:

- `yiisoft/yii2-php`
- `yiisoft/yii2-php:7`
- `yiisoft/yii2-php:7.1.2-fpm`
- `yiisoft/yii2-php:5.6-alpine`
- `yiisoft/yii2-php:8-rhel`

**Comment by mikehaertl** [comment]
And there *will* be Yii2 specific changes in some images. E.g. we'll probably include the Apache config for apache based images. So it's not just a PHP image. It can only be used with yii2.
