### ISSUE TITLE
Why there is no not privileged user in the image?

### ISSUE THREAD

**Issue by danjudex** [yiisoft/yii2-docker#47]
when I connect to the console
docker-compose exec php bash
my user is root
in laradock project for example used --user=laradock
I need run code ./yii with PHP_USER_ID UID 
Maybe add user www-data with rights to bash login? Or add user php.

**Comment by samdark** [comment]
Good idea. @schmunk42 what do you think?

**Comment by schmunk42** [comment]
Basically yes, if it is intuitive. One reason there's nothing by default was related to Alpine, which has no `usermod` by default so you can't really switch the user.

From my experience, I find it OK to be `root` when I run `exec bash`, since there's hardly anything I want to do as an unprivileged user here. Examples welcome.

While our app (when running `yii`) usually runs as the same user as the webserver, ie. to prevent permission issues for directories, etc... when I need to run this "as root" I usually prepend `PHP_USER_ID=0 yii` to the command (which could also be aliased as `suyii`).

**Comment by danjudex** [comment]
why not install the package usermod in image for compatibility?

RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
RUN apk --no-cache add shadow

**Comment by schmunk42** [comment]
> why not install the package usermod in image for compatibility?

Last time I tried this it required several hundred megabytes of additional packgages. 

Moreover Alpine has highly esoteric issues, see also https://github.com/docker-library/docs/blob/master/php/README.md#phpalpine

**Comment by danjudex** [comment]
docker image ls
```
alpine-usermod        latest              95405d664f72        4 minutes ago       6.13MB
alpine                latest              3fd9065eaf02        5 months ago        4.15MB
```

Dockerfile
```
FROM alpine

RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
RUN apk --no-cache add shadow
```

**Comment by schmunk42** [comment]
It's good if it is so easy now, but it's not planned to support Alpine anyway.

**Comment by schmunk42** [comment]
You can do this with Debian images like so:

```
docker-compose exec -u www-data php bash
www-data@bffa62a55ea8:/app$ whoami
www-data
```
