### ISSUE TITLE
PHP 7.4 image

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-docker#82]
See https://github.com/yiisoft/yii-docker recent commits.

**Comment by szabozoltan69** [comment]
Please change in Dockerfile-debian:

-        --with-freetype-dir=/usr/include/ \
-        --with-png-dir=/usr/include/ \
-        --with-jpeg-dir=/usr/include/ && \

+        --with-freetype \
+        --with-jpeg && \

...according to https://github.com/docker-library/php/issues/912  - only with with-freetype + --with-jpeg

**Comment by schmunk42** [comment]
New builds are blocked by https://github.com/yiisoft/yii2/issues/17708

**Comment by schmunk42** [comment]
@samdark Tests do not pass, the formatter function (or test) in question should be fixed, but looks not that trivial, I created a PR but it did not run as expected.

Tests are run in Docker build to ensure the framework and PHP version work flawlessly.

**Comment by salazar-ibw** [comment]
In the linked issue, the discussion seems to indicate that this test can be skipped. Is something else holding up the php 7.4 images ?

**Comment by schmunk42** [comment]
Finally it is working, Apache is already there https://hub.docker.com/layers/yiisoftware/yii2-php/7.4-apache/images/sha256-46b2068f021e21976bd9cfa647d6f35a81dfd344caea1d5cafd1453669738e7a?context=repo and fpm should be in a few minutes.

After waiting weeks for a response from travis with no solution, the fix was to upgrade `docker-compose` - but I don't know why :man_shrugging: ...anyway, happy dockering.
